# Generated by Django 4.2.6 on 2023-11-22 16:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_date_termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio_hora',
            field=models.TimeField(default=datetime.time(13, 4, 16, 115194)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_termino',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_termino_hora',
            field=models.TimeField(default=datetime.time(13, 5, 12, 586318)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_tiempo_inicio',
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
