# Generated by Django 4.2.6 on 2023-12-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='archivos_adjuntos',
        ),
        migrations.DeleteModel(
            name='ArchivoSolicitud',
        ),
    ]
