# Generated by Django 4.2.6 on 2023-12-04 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_solicitud_archivos_adjuntos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudarchivo',
            old_name='solicitud',
            new_name='id_solicitud',
        ),
        migrations.AddField(
            model_name='solicitudarchivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='archivos_adjuntos',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='archivos_adjuntos',
            field=models.ManyToManyField(blank=True, null=True, to='proyectos.solicitudarchivo'),
        ),
    ]
