# Generated by Django 4.2.6 on 2023-12-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_rename_id_solicitud_solicitudarchivo_campo_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='archivos_adjuntos',
            field=models.ManyToManyField(blank=True, related_name='solicitudes', to='proyectos.solicitudarchivo'),
        ),
    ]
