# Generated by Django 4.2.6 on 2023-12-04 03:08

from django.db import migrations, models
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_solicitud_archivos_adjuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarchivo',
            name='archivo',
            field=models.FileField(upload_to=proyectos.models.ruta_solicitudes_archivos),
        ),
    ]
