# Generated by Django 4.2.6 on 2023-12-04 03:57

from django.db import migrations, models
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_remove_solicitud_archivos_adjuntos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='archivos_adjuntos',
        ),
        migrations.DeleteModel(
            name='SolicitudArchivo',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, upload_to=proyectos.models.ruta_solicitudes_archivos),
        ),
    ]
