# Generated by Django 4.2.6 on 2023-12-04 04:20

from django.db import migrations, models
import django.db.models.deletion
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_remove_solicitud_archivos_adjuntos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='archivos_adjuntos',
        ),
        migrations.CreateModel(
            name='SolicitudArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=proyectos.models.ruta_solicitudes_archivos)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='archivos_adjuntos',
            field=models.ManyToManyField(blank=True, related_name='archivos_adjuntos', to='proyectos.solicitudarchivo'),
        ),
    ]
