# Generated by Django 4.2.6 on 2023-12-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_remove_solicitud_archivos_adjuntos_solicitudarchivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='proyecto_en_marcha',
            new_name='fin_del_proyecto',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='proyecto_fin_marcha',
            new_name='inicio_del_proyecto',
        ),
    ]
