# Generated by Django 4.2.6 on 2023-11-07 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_inscripcion_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_creacion_actividad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
