# Generated by Django 4.2.6 on 2023-11-22 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_fecha_creacion_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_actividad_tiempo_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_actividad_tiempo_termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
