# Generated by Django 4.2.6 on 2023-11-28 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_fecha_actividad_tiempo_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='fecha_actividad_tiempo_inicio',
            new_name='cierre_inscripcion',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='fecha_actividad',
            new_name='fin_actividad',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='fecha_actividad_tiempo_termino',
            new_name='inicio_inscripcion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='hora_termino',
        ),
        migrations.AddField(
            model_name='actividad',
            name='inicio_actividad',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
