# Generated by Django 4.2.6 on 2023-12-04 17:27

import actividades.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_rename_fecha_actividad_tiempo_inicio_actividad_cierre_inscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=actividades.models.ruta_solicitudes_archivos)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campo_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.inscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='archivos_adjuntos',
            field=models.ManyToManyField(blank=True, null=True, related_name='archivos_adjuntos', to='actividades.solicitudinscripcion'),
        ),
    ]
