# Generated by Django 4.2.6 on 2023-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.CharField(default='hola', max_length=200),
            preserve_default=False,
        ),
    ]
