# Generated by Django 4.2.6 on 2023-11-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='texto',
        ),
    ]
